In [1]:
import torch

## Pytorch Version

In [2]:
print(torch.__version__)

2.5.1+cpu


Introduction to tensors

In [3]:
# Scalar number or Zero Dimension Tensor

scalar = torch.tensor(7)
print(scalar)

# tensor(7) means 7 is of type tensor

# To check dimension of tensor, use ndim
print(f"Dimension of tensor: {scalar.ndim}")

# To Retrive number/value from the tensor, use item

print(scalar.item())

tensor(7)
Dimension of tensor: 0
7


In [4]:
# Vector : Single dimesnion vector, just like 1D array. Can contain many numbers.

vector = torch.tensor([0, 1])
print(vector)

print(f"Dimension of vector: {vector.ndim}")

print(f"Shape of tensor: {vector.shape}")

print(vector[0].item())

tensor([0, 1])
Dimension of vector: 1
Shape of tensor: torch.Size([2])
0


In [5]:
# Matrix, same as vector but has 2D
Matrix = torch.tensor([[0, 1],
                       [3, 4]])

print(Matrix)

print(Matrix.ndim)

print(Matrix.shape)
print(Matrix[0][0].item())
# Two vector with shape of 2 i.e. [2,2]

tensor([[0, 1],
        [3, 4]])
2
torch.Size([2, 2])
0


In [6]:
# Tensor, n-Dimension
Tensor = torch.tensor([[0, 1],
                       [3, 4],
                       [5,6]])

print(Tensor)

print(Tensor.ndim)

print(Tensor.shape)
# Two vector with shape of 2 i.e. [2,2]

tensor([[0, 1],
        [3, 4],
        [5, 6]])
2
torch.Size([3, 2])


In [7]:
# Tensor, n-Dimension
Tensor = torch.tensor([[[0, 1],
                       [3, 4],
                       [5,6]]])

print(Tensor)

print(Tensor.ndim)

print(Tensor.shape)
# 1,3,2 means 1 dimension of shape 3,2
# torch.Size([1,3,2]) means dim_0 = 1, dim_1 = 3, dim_2 = 2

# Indexing
print("=="*20)
print(Tensor[0]) # First Square Bracket
print(Tensor[0][0]) # Second Square Bracket
print(Tensor[0][0][0]) # Third Square Bracket

print("=="*20)
print(Tensor[:, 0])
'''
Get all values of 0th dimesnion and 0th index of 1st demension (row)
'''
print(Tensor[:,:,1])
'''
Get all values of 0th & 1st dimensions but only index 1 of 2nd dimension
i.e. 0th dimesion is outer square bracket, 1st dimension is row, 2nd dimesnion (column)
is column bring all the values from column
'''
print(Tensor[:,2,1])
'''
Get all values of 0th dimesnion and 1st index of 1st demension (row) and 1st index from 2nd dimesion (column)
'''

tensor([[[0, 1],
         [3, 4],
         [5, 6]]])
3
torch.Size([1, 3, 2])
tensor([[0, 1],
        [3, 4],
        [5, 6]])
tensor([0, 1])
tensor(0)
tensor([[0, 1]])
tensor([[1, 4, 6]])
tensor([6])


'\nGet all values of 0th dimesnion and 1st index of 1st demension (row) and 1st index from 2nd dimesion (column)\n'

In [8]:
# Tensor, n-Dimension
Tensor = torch.tensor([[[0, 1, -1],
                       [3, 4, -2],
                       [5,6, -3]]])

print(Tensor)

print(Tensor.ndim)

print(Tensor.shape)
# 1,3,3 means 1 dimension of shape 3,3
# torch.Size([1,3,3]) means dim_0 = 1, dim_1 = 3, dim_2 = 3

tensor([[[ 0,  1, -1],
         [ 3,  4, -2],
         [ 5,  6, -3]]])
3
torch.Size([1, 3, 3])


In [ ]:
## 0 Dimesnion tensor is scalar, 1 Dimension tensor is vector, 2 Dimension tensor is Matric and all of them are tensors. Tensor is n-dimesnion array of numbers.

# Random Numbers


In [9]:
random_tensor = torch.rand(size=(3, 4))
# 3,4 = c x r or or 3 vectors of shape 4

print(random_tensor)

print(random_tensor.ndim)

print(random_tensor.shape)

tensor([[0.3135, 0.4153, 0.3220, 0.6121],
        [0.5826, 0.9716, 0.2937, 0.2539],
        [0.4604, 0.0607, 0.2860, 0.8264]])
2
torch.Size([3, 4])


In [11]:
import torch
import numpy as np
import cv2

# Generate random image noise
random_image_tensor = torch.rand(size=(150, 150, 3))

# Convert the tensor to a NumPy array
random_image_np = random_image_tensor.numpy()

# Rescale to [0, 255] for 8-bit image
random_image_np = (random_image_np * 255).astype(np.uint8)

# Display the image using OpenCV
cv2.imshow("Random Noise Image", random_image_np)
cv2.waitKey(0)  # Wait until a key is pressed
cv2.destroyAllWindows()

# If you try different scaling, clip the values to make sure they are in the valid range
random_image_np = (random_image_tensor.numpy() * 500).clip(0, 255).astype(np.uint8)
cv2.imshow("Scaled Noise Image", random_image_np)
cv2.waitKey(0)  # Wait until a key is pressed
cv2.destroyAllWindows()


# Tensor of zero's and one's

In [12]:
# Create a tensor of all zeros
zeros = torch.zeros(size=(3, 4))
print(zeros)
print(zeros.dtype) # to check dataype of tensor

# Create a tensor of all ones
ones = torch.ones(size=(3, 4))
print(ones)
print(ones.dtype) # to check dataype of tensor

tensor([[0., 0., 0., 0.],
        [0., 0., 0., 0.],
        [0., 0., 0., 0.]])
torch.float32
tensor([[1., 1., 1., 1.],
        [1., 1., 1., 1.],
        [1., 1., 1., 1.]])
torch.float32


In [13]:
# Creating range of values

range = torch.arange(start=0, end=20)
print(range)

range = torch.arange(start=0, end=20, step=2)
print(range)

tensor([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14, 15, 16, 17,
        18, 19])
tensor([ 0,  2,  4,  6,  8, 10, 12, 14, 16, 18])


In [15]:
# Using shape of other tensor to create zero tensor

import torch
import numpy as np
import cv2

# Create a tensor of zeros with the same shape as random_image_tensor
dummy_image_zeros = torch.zeros_like(random_image_tensor)

# Convert the tensor to a NumPy array
dummy_image_zeros_np = dummy_image_zeros.numpy()

# Rescale to [0, 255] for display (although this is redundant since it's all zeros)
dummy_image_zeros_np = dummy_image_zeros_np.astype(np.uint8)

# Display the dummy image (all black)
cv2.imshow("Dummy Image with Zeros", dummy_image_zeros_np)
cv2.waitKey(0)  # Wait until a key is pressed
cv2.destroyAllWindows()


In [16]:
# Using shape of other tensor to create zero tensor

import torch
import numpy as np
import cv2

# Create a tensor of ones with the same shape as random_image_tensor
dummy_image_ones = torch.ones_like(random_image_tensor)

# Convert the tensor to a NumPy array
dummy_image_ones_np = dummy_image_ones.numpy()

# Rescale to [0, 255] for display (scaled to 255 for display as white)
dummy_image_ones_np = (dummy_image_ones_np * 255).astype(np.uint8)

# Display the dummy image (all white)
cv2.imshow("Dummy Image with Ones", dummy_image_ones_np)
cv2.waitKey(0)  # Wait until a key is pressed
cv2.destroyAllWindows()


Pytorch has different precision type for each type of data types. Precision is the amount of detail used to describe a number. If we want more amount of detail, we need more precise dtype.
Floating point type :

* Default dtype of a tensor is torch.float32 or torch.float

* Half of default is torch.float16 or torch.half  

* Double of default is torch.float64 or torch.double

Integer dtype :

* torch.int8

* torch.int16 or torch.short

* torch.int32 or torch.int

* torch.int64 or torch.long

Boolean dtype :

* torch.bool


In [17]:
# Default datatype for tensors is float32
tensor_example = torch.tensor([0, 1, 2],
                          dtype=None, # defaults to None, which is torch.int64 or whatever datatype is passed
                          device=None, # defaults to None, which uses the default tensor type
                          requires_grad=False) # if True, operations performed on the tensor are recorded

print(tensor_example)

print(tensor_example.dtype)

print(tensor_example.device)

tensor([0, 1, 2])
torch.int64
cpu


In [18]:
# Default datatype for tensors is float32
tensor_example = torch.tensor([0., 1., 2.],
                          dtype=None, # defaults to None, which is torch.float32 or whatever datatype is passed
                          device=None, # defaults to None, which uses the default tensor type
                          requires_grad=False) # if True, operations performed on the tensor are recorded

print(tensor_example)

print(tensor_example.dtype)

print(tensor_example.device)

tensor([0., 1., 2.])
torch.float32
cpu


In [19]:
# Default datatype for tensors is float32
tensor_example = torch.tensor([0, 1, 2], dtype=torch.float64)

print(tensor_example)

print(tensor_example.dtype)

print(tensor_example.device)

tensor([0., 1., 2.], dtype=torch.float64)
torch.float64
cpu


# Manupulating Tensors

In [20]:
tensor_t = torch.tensor([1,2,3,4])

# Adition
print(tensor_t + 10)
print(torch.add(tensor_t, 10))

# Subtraction
print(tensor_t - 10)
print(torch.subtract(tensor_t, 10))

# Multiplication
print(tensor_t * 10)
print(torch.mul(tensor_t, 10))

# Division
print(tensor_t / 10)
print(torch.div(tensor_t, 10))

tensor([11, 12, 13, 14])
tensor([11, 12, 13, 14])
tensor([-9, -8, -7, -6])
tensor([-9, -8, -7, -6])
tensor([10, 20, 30, 40])
tensor([10, 20, 30, 40])
tensor([0.1000, 0.2000, 0.3000, 0.4000])
tensor([0.1000, 0.2000, 0.3000, 0.4000])


In [21]:
# Element wise multiplication

print(tensor_t * tensor_t)

tensor([ 1,  4,  9, 16])


In [22]:
# Matrix Multiplication or DOT Product

'''
For a successful matrix operation, we need to consider few things

* Matrix Inner Dimesnion Should Match
- matrix_a.shape = X, Y
- matrix_b.shape = A, B
Condition --> Y == A

* Resulting Matrix will have the shape of Outer Dimesnion
- matrix_a.shape = X, Y
- matrix_b.shape = A, B
Output --> X, B
'''

print(torch.matmul(tensor_t, tensor_t))
# [1*1 + 2*2 + 3*3 + 4*4]
# [1 + 4 + 9 + 16]
# [10 + 20] = [30]

tensor(30)


In [23]:
tensor_a = torch.tensor([[1,2],
                         [2,3],
                         [3,4]])
tensor_b = torch.tensor([[1,2],
                         [2,3],
                         [3,4]])

try:
  print(torch.matmul(tensor_a, tensor_b))
except Exception as e:
  print(f"We are trying to multiply tensor of same shape, Rule is that inner dimension should match. Error : {e}")

We are trying to multiply tensor of same shape, Rule is that inner dimension should match. Error : mat1 and mat2 shapes cannot be multiplied (3x2 and 3x2)


In [24]:
tensor_a = torch.tensor([[1,2],
                         [2,3],
                         [3,4]])
tensor_b = torch.tensor([[1,2],
                         [2,3],
                         [3,4]])

# Perform transpose on a Matrix
try:
  print(tensor_a.shape, tensor_b.T.shape)
  print(torch.matmul(tensor_a, tensor_b.T))
  print(torch.mm(tensor_a, tensor_b.T))
except Exception as e:
  print(f"We are trying to multiply tensor of same shape, Rule is that inner dimension should match. Error : {e}")

torch.Size([3, 2]) torch.Size([2, 3])
tensor([[ 5,  8, 11],
        [ 8, 13, 18],
        [11, 18, 25]])
tensor([[ 5,  8, 11],
        [ 8, 13, 18],
        [11, 18, 25]])


# Matrix Aggregation

In [25]:
tensor_agg = torch.tensor([1,2,3,4,5,6,7,8,9,10])
print(f"Minimum: {tensor_agg.min()}")
print(f"Maximum: {tensor_agg.max()}")
print("-"*20)
try:
  print(f"Mean: {tensor_agg.mean()}") # won't work without float datatype
except Exception as e:
  print(f"Exception : {e}")
  print(tensor_agg.dtype)
  # Syntax : tensor.type(torch.datatype)
  print(f"Mean: {tensor_agg.type(torch.float32).mean()}") # won't work without float datatype

print("-"*20)

print(f"Index where max value occurs: {tensor_agg.argmax()}")
print(f"Maximum Value at index {tensor_agg.argmax()} : {tensor_agg[tensor_agg.argmax()].item()}")

print("-"*20)

print(f"Index where min value occurs: {tensor_agg.argmin()}")
print(f"Minimum Value at index {tensor_agg.argmin()} : {tensor_agg[tensor_agg.argmin()].item()}")

Minimum: 1
Maximum: 10
--------------------
Exception : mean(): could not infer output dtype. Input dtype must be either a floating point or complex dtype. Got: Long
torch.int64
Mean: 5.5
--------------------
Index where max value occurs: 9
Maximum Value at index 9 : 10
--------------------
Index where min value occurs: 0
Minimum Value at index 0 : 1
